# Numpy(Numerical Python)
- Numpy는 Numerical Python의 약자로 과학 및 공학 분야에서 사용되는 오픈 소스 파이썬 라이브러리이다.
- Numpy 라이버르리에는 다차원 배열 및 행렬 데이터 구조가 포함되어 있다.
- Numpy는 배열로 저장된 값에 대한 수학 연산을 수행하는데 사용된다.

In [ ]:
! pip install numpy # 넘파이 설치

In [ ]:
! pip list # 설치된 라이브러리 목록 확인

In [13]:
import numpy as np

In [19]:
city = ['seoul','busan','ulsan']
print(city[0])

seoul


In [29]:
city = np.array(['seoul','busan','ulsan'])
print(city[0])
print(type(city))
print(city.dtype)

seoul
<class 'numpy.ndarray'>
<U5


In [35]:
arr = np.array([2,4,6,8,10]) # 일반적인 형태
#arr = np.array((3,5,6,8,10))
print(arr)
print(type(arr))
print(arr.dtype)

[ 3  5  6  8 10]
<class 'numpy.ndarray'>
int32


### 리스트와 넘파이 비교

In [40]:
# 리스트 형태
a = [1,3,5]
b = [2,4,6]

print(a+b)

[1, 3, 5, 2, 4, 6]


In [44]:
print(a * b) # 에러발생

In [46]:
print(a *3)

[1, 3, 5, 1, 3, 5, 1, 3, 5]


In [48]:
print(a[1] +b[1])

7


In [50]:
# 넘파이 형태
a = np.array([1,3,5])
b = np.array([2,4,6])

print(a[1]+b[1])

7


In [52]:
print(a+b)

[ 3  7 11]


In [54]:
print(a * b)

[ 2 12 30]


In [56]:
print(a *3)

[ 3  9 15]


In [68]:
c = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) # 리스트를 넘파이로 변환
#print(f"2단:", c *2)
#print(f"3단:", c *3)
for i in range(1,10):
    print(f"{i}단:", c *i)
    

2단: [ 2  4  6  8 10 12 14 16 18]
3단: [ 3  6  9 12 15 18 21 24 27]
1단: [1 2 3 4 5 6 7 8 9]
2단: [ 2  4  6  8 10 12 14 16 18]
3단: [ 3  6  9 12 15 18 21 24 27]
4단: [ 4  8 12 16 20 24 28 32 36]
5단: [ 5 10 15 20 25 30 35 40 45]
6단: [ 6 12 18 24 30 36 42 48 54]
7단: [ 7 14 21 28 35 42 49 56 63]
8단: [ 8 16 24 32 40 48 56 64 72]
9단: [ 9 18 27 36 45 54 63 72 81]


In [81]:
res = c * 5
print(res)
print(type(res))
lres = res.tolist()  # 넘파이를 리스트로 변환
print(lres)
print(type(lres))

[ 5 10 15 20 25 30 35 40 45]
<class 'numpy.ndarray'>
[5, 10, 15, 20, 25, 30, 35, 40, 45]
<class 'list'>


In [84]:
import numpy as np

# 1차원간 배열 연산
a= np.array([1,2,3])
b= np.array([10,20,30])

print(a + b)
print(a * b)
print(a / b)

[11 22 33]
[10 40 90]
[0.1 0.1 0.1]


### 사례

In [96]:
import numpy as np

# 체질량 지수(BMI)
heights = np.array([170,175,160])     # 키(cm)
weights = np.array([60,70,55])       # 몸무게

# BMI = 몸무게 /(키/100)^2
# 저체중 : BMI < 18.5
# 정상 : 18.5 <= MBI < 24.9
# 과체중 : 25<= BMI < 29.9
# 비만 : BMI >= 30

bmi = weights / (heights/100)**2
print("BMI:", bmi)


BMI: [20.76124567 22.85714286 21.484375  ]


In [102]:
a= np.array([1, 2, 3]) # 값 개수가 안맞으면 계산이 안된다. (3개,2개)
c = np.array([1, 2])
print(a + c)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [114]:
## 

import numpy as np

# 행 : 학생별 / 열:과목별
# axis = 0: 세로방향(열)
# axis = 1: 가로방향(행)
scores =np.array([[85,90,88,95],
                  [92,87,85,89],
                  [78,85,91,87]])
# 과목별 평균
subject_mean = scores.mean(axis=0)
print(f"과목별 평균: ",subject_mean)
# 학생별 평균
student_mean = scores.mean(axis=1)
print(f"학생별 평균: ",student_mean)

# 정규화
nml = scores - subject_mean
print(nml)

과목별 평균:  [85.         87.33333333 88.         90.33333333]
학생별 평균:  [89.5  88.25 85.25]
[[ 0.          2.66666667  0.          4.66666667]
 [ 7.         -0.33333333 -3.         -1.33333333]
 [-7.         -2.33333333  3.         -3.33333333]]


In [130]:
# 학생들의 점수 (행: 학생 열:과목)
scores = np.array([[90,85,88,75],   # 학생1
                   [85,92,87,98],   # 학생2
                   [88,86,91,90]])  # 학생3

# 과목별 가중치(40%, 30%, 20%, 10%)
w = np.array([0.4, 0.3, 0.2,0.1])
wscore = scores * w
print(wscore)
# 가중치가 반영된 학생별 평균 점수
fscore = wscore.sum(axis=1)
print(fscore)

[[36.  25.5 17.6  7.5]
 [34.  27.6 17.4  9.8]
 [35.2 25.8 18.2  9. ]]
[86.6 88.8 88.2]


In [138]:
## 상품가격 할인율 계산

# 상품가격 : 12000,35000,8000,45000,28000
# 할인률 : 10,20,5,30,15
# 할인률이 적용된 가격은
product = np.array([12000,35000,8000,45000,28000])
discount = np.array([10,20,5,30,15])
a =  product-(product/100 * discount)
print(a)

[10800. 28000.  7600. 31500. 23800.]


In [270]:
import numpy as np

# 상품 가격(원)
prices = np.array([50000,150000,250000,80000,120000])
discount= []

for price in prices:
    if price < 100000:
        discount.append(10)
    elif 100000 <= price < 200000:
        discount.append(15)
    else:
        discount.append(20)

discounts = np.array(discount)

final_prices = prices - (prices * discounts / 100)

print(final_prices)



[ 45000. 127500. 200000.  72000. 102000.]


In [274]:
import numpy as np

# 상품 가격(원)
prices = np.array([50000, 150000, 250000, 80000, 120000])

# 할인율을 저장할 리스트
discounts = []

# 각 상품에 대한 할인율 계산
for price in prices:
    if price < 100000:             # 10만원 미만
        discounts.append(10)
    elif 100000 <= price < 200000: # 20만원 미만
        discounts.append(15)
    else:                          # 20만원 이상
        discounts.append(20)

# 할인율 배열로 변환
discounts = np.array(discounts)

# 최종 가격 계산
final_prices = prices - (prices * discounts / 100)

print(final_prices)


[ 45000. 127500. 200000.  72000. 102000.]


In [272]:
import numpy as np

# 상품 가격(원)
prices = np.array([50000,150000,250000,80000,120000])
## 할인 조건 : 10만원 미만-10% 20만원 미만 15% 20만원 이상 20%할인
def get_discount_rate(price):
    if price < 100000:
        return 10
    elif 100000 < price < 200000:
        return 15
    else:
        return 20

discounts = np.array( [get_discount_rate(price) for price in prices])

discount_amout = prices * (discounts/100)
fprice = prices - discount_amout

print(fprice)


[ 45000. 127500. 200000.  72000. 102000.]


In [280]:
# 5일간 3개 도시의 온도(섭씨)
temps_c = np.array([[25,27,26,24,23],  # 서울
                    [28,30,29,27,26],  # 부산
                    [22,24,23,21,20]   # 강릉
                   ])

# 섭씨 --> 화씨: F(c * 9/5) + 32
temps_f = (temps_c * 9/5) + 32

print("화씨 온도:\n",temps_f)


화씨 온도:
 [[77.  80.6 78.8 75.2 73.4]
 [82.4 86.  84.2 80.6 78.8]
 [71.6 75.2 73.4 69.8 68. ]]


In [296]:
import numpy as np

# 의류 상품 가격(원)
clothing_prices = np.array([25000,60000,15000,80000,120000])

# 의류 상품별 할인율(%)
clothing_discounts = np.array([15,25,10,50,20])

discount_f = 1 - (clothing_discounts / 100)
final_price = clothing_prices * discount_f
print('할인 금액:',final_price)

할인 금액: [21250. 45000. 13500. 40000. 96000.]


In [304]:
import numpy as np

# 3개 지점의 일주일 매출 데이터
sales = np.array([[520000, 480000, 510000, 690000, 620000, 750000, 510000],  # 1호점
                  [480000, 460000, 490000, 670000, 580000, 710000, 490000],  # 2호점
                  [590000, 520000, 550000, 720000, 650000, 780000, 540000]]) # 3호점
daily_avg = sales.mean(axis=0)
print(daily_avg)
perfomance = (sales/ daily_avg *100) -100 # 평균 대비 퍼센트

print("요일별 평균 대비 성과 (%):\n",perfomance)

[530000.         486666.66666667 516666.66666667 693333.33333333
 616666.66666667 746666.66666667 513333.33333333]
요일별 평균 대비 성과 (%):
 [[-1.88679245 -1.36986301 -1.29032258 -0.48076923  0.54054054  0.44642857
  -0.64935065]
 [-9.43396226 -5.47945205 -5.16129032 -3.36538462 -5.94594595 -4.91071429
  -4.54545455]
 [11.32075472  6.84931507  6.4516129   3.84615385  5.40540541  4.46428571
   5.19480519]]
