## 0차원 배열 (스칼라)
- 하나의 데이터 값을 가진 배열


In [12]:
import numpy as np

arr =np.array(12)
print(arr)
print(type(arr))
# shape(): 배열이 무슨 차원으로 구성되어 있는지 보여줌
print(np.shape(arr)) # 0차원에서는 반환값이 없음

12
<class 'numpy.ndarray'>
()


## 1차원 배열(백터)
- 넘파이 배열의 가장 기본적인 배열을 말한다.
- 1차원 배열은 파이썬의 리스트(list)와 동일한형태를 가진다.

In [16]:
import numpy as np
arr = np.array([2,4,6,8,10])
print(arr)
print(np.shape(arr))

[ 2  4  6  8 10]
(5,)


In [52]:
# 넘파이 초기화

print(np.zeros(5)) # 0으로 채워진 1차원 배열 생성
print(np.ones(5)) # 1로 채워진 1차원 배열 생성
print(np.empty(5))  # 빈 배열 생성, 메모리 상태에 따라 다름다(바로 값을 넣으려고 만든 경우)
print(np.arange(5))  #0부터 5개 숫자 형성[0 1 2 3 4]

arr =np.empty(5)
arr[:] =np.arange(1,6)
print(arr)

print(np.arange(2,20,3)) # 2 ~ 19 ,step:3, 일정한 간격의 배열 생성(시작,정지,단계(step))
print(np.linspace(0,100,num=3))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[0 1 2 3 4]
[1. 2. 3. 4. 5.]
[ 2  5  8 11 14 17]
[  0.  50. 100.]


In [56]:
import numpy as np
scores= np.array([90,80,100,85,98])
print(scores)
scores = np.zeros(5)
print(scores)

[ 90  80 100  85  98]
[0. 0. 0. 0. 0.]


In [58]:
# 5명의 출석 상태를 1로 초기화
num_students = 5
attepdance =np.zeros(num_students)
print("Inital Scores:",scores)

# 점수 입력 (예시)

scores[0] =85
scores[1] =90
print("Updated Scores:",scores)

Inital Scores: [0. 0. 0. 0. 0.]
Updated Scores: [85. 90.  0.  0.  0.]


## 2차원 배열(매트릭스:행렬)
- 2-차원 배열을 행렬(Matrix)이라고 한다.
- 2-차원 배열은 테이블(표) 형태과 같이 행과 열로 구성된 배열이다.

In [63]:
import numpy as np
arr = np.array([
                [2,4,6],
                [1,3,5]
                ]) # 2행 3열
print(arr)
print(np.shape(arr))

[[2 4 6]
 [1 3 5]]
(2, 3)


In [67]:
import numpy as np
arr =np.array([[2,4],[6,8],[10,12]]) # 3행 ,2열
print(arr)
print(np.shape(arr))

[[ 2  4]
 [ 6  8]
 [10 12]]
(3, 2)


In [69]:
print(len(arr))  # 행의 개수를 표시
print(len(arr[0])) # 열의 개수를 표시

3
2


In [71]:
arr = np.array([[85,90,78,92],
                [75,80,88,70],
                [95,100,90,85]])
print(np.shape(arr))
print(len(arr))    # 행 수
print(len(arr[0])) # 열 수

(3, 4)
3
4


In [79]:
# 5종 제품의 재고 수량과 가격
arr =np.array([[10,100],
               [5,200],
               [20,50],
               [0,150],
               [15,80]])
print(np.shape(arr))
print(len(arr))    # 행 수
print(len(arr[0])) # 열 수
print(arr.shape)          # 배열의 크기(튜플로 반환)
print(arr.ndim,"차원")    # 배열의 차원 수 : 0 1 2 3

(5, 2)
5
2
(5, 2)
2 차원


## 3차원 배열(텐서)
- 3-차원 이상의 배열을 텐서(Tensor)라고 한다.
- 3-차원 배열은 2-차원 배열을 몇번 사용하는지에 따라 깊이가 결정된다

In [87]:
import numpy as np
arr = np.array([[[111,112,113], [121,122,123]],
                [[211,212,213], [221,222,223]],
                [[311,312,313], [321,322,323]],
                [[411,412,413], [421,422,423]]
               ])
print(arr)
print(np.shape(arr))

[[[111 112 113]
  [121 122 123]]

 [[211 212 213]
  [221 222 223]]

 [[311 312 313]
  [321 322 323]]

 [[411 412 413]
  [421 422 423]]]
(4, 2, 3)


In [89]:
print(len(arr))        # 깊이(총)를 표시
print(len(arr[0]))     # 형의 개수를 표시
print(len(arr[0][0]))  # 열의 개수를 표시 

4
2
3


## 배열의 재구성
- 배열 재구성(reshpae)은 데이터를 변경하지 않고 배열의 크기를 변경하는 것을 말한다.
- 배열 크기를 변경할 때 원래 배열과 동일한 수의 데이터를 가져야 한다.
- 1-차원 배열의 데이터 수가 6 개라면 새롭게 변경하는 2-차원 배열의 데이터 수도 6개이어야 한다.

In [101]:
# reshape 시 전체 원소 개수는 유지되어야함

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) # 넘파이 배열 1차원 ---> 2차원 (4, 3)(2, 6)
print(arr)
#new1 =np.reshape(arr,(4,3))
#new2 =np.reshape(arr,(2,6))
new1 =arr.reshape(4,3)
new2 =arr.reshape(6,2)
print(new1)
print(new2)
# 2차원 ----> 1차원
new3 = new2.flatten()
print(new3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [105]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] # 리스트
new1 =np.reshape(a,(4,3))
new2 =np.reshape(a,(2,6))
new3 =np.reshape(a,(1,12))
print(new1,'\n')
print(new2)
print(*new3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [109]:
# 1차원 ---> 3차원 배열크기 변경
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new4 = arr.reshape(2,3,2)
print(new4)
print(new4.shape)
print(new4.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
3


## 배열의 차원 수를 확장하기
- 넘파이 newaxis 함수를 사용하여 기본 배열의 크기(차원수)를 확장할 수 있다.
- newaxis 함수는 배열의 크기를 한 차원 늘리는 것으로 1-차원 배열을 2-차원배열로,2-차원 배열을 3-차원 배열로 재구성해 준다.
- np.newaxis로 새로운 축을 추가할 때, 그 축의 크기는 항상 1이 됩니다. 이것은 numpy의 설계된 방식

In [116]:
import numpy as np
new = np.array([1, 2, 3, 4, 5, 6])
print(new)
print(new.shape)
newarr =new[np.newaxis,:]
print(newarr)
print(newarr.shape)
newarr2 =new[:,np.newaxis]
print(newarr2)
print(newarr2.shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3 4 5 6]]
(1, 6)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [124]:
import numpy as np
arr = np.array([1, 2, 3, 4])

row_vector = arr[np.newaxis,:]
col_vector = arr[:,np.newaxis]
print(arr.shape)

print(row_vector.shape) # (1,4)
print(row_vector)
print(col_vector.shape) # (4,1) 
print(col_vector)

(4,)
(1, 4)
[[1 2 3 4]]
(4, 1)
[[1]
 [2]
 [3]
 [4]]


## 넘파이 인덱싱
- 파이썬 리스트(list)의 데이터를 인덱싱할 수 있는 것과 같이 넘파이 배열 또한 데이터를 인덱싱할 수 있다.
- 넘파이 배열의 인덱싱 방법은 리스트(list)의 인덱싱 방법과 동일하다. 즉 인덱스 번호를 참조하여 배열에 저장된 특정 데이터를 찾을 수 있다.
- 넘파이 배열의 인덱스는 0 으로 시작하므로 첫 번쨰 데이터의 인덱스는0, 두 번째 데이터의 인덱스는 1로 표시한다.


In [127]:
# 1차원 인덱싱
import numpy as np
arr = np.array([2, 4, 6, 8])
arr[0]


2

In [129]:
# 1차원 인덱싱
import numpy as np
arr = np.array([2, 4, 6, 8])
print(arr[1] + arr[3])
print(arr[1] * arr[3])

12
32


In [131]:
# 2차원 인덱싱
arr =np.array([[2, 4, 6], [1, 3, 5]])
arr

array([[2, 4, 6],
       [1, 3, 5]])

In [133]:
arr[0,1]

4

In [137]:
arr[1,2]

5

In [145]:
# 3차원 인덱싱
import numpy as np
arr = np.array([[[11,12,13],[14,15,16]],
              [[21,22,23],[24,25,26]]])
arr # (2, 2, 3)
print(arr.shape)

(2, 2, 3)


In [147]:
print(arr[0,0,0])

11


In [149]:
print(arr[1,0,0])

21


In [151]:
print(arr[1,1,2])

26


## 음수 인덱싱

In [154]:
import numpy as np
arr =np.array([2, 4, 6, 8])
arr[-1]

8

In [158]:
import numpy as np
arr =np.array([[2, 4, 6],[1, 3, 5]])
arr[1,-2]
arr[-1,-2]

3

## 조건에 맞는 요소 인덱싱
- 특정 조건에 맞는 데이터만을 인덱싱할 수 있다.
- 부울리안(True,False)값으로 표시.

In [161]:
import numpy as np
arr =np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr < 5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [174]:
arr[arr < 5]

array([1, 2, 3, 4])

In [176]:
arr[arr > 8]

array([ 9, 10, 11, 12])

In [178]:
arr[arr % 2 ==0]

array([ 2,  4,  6,  8, 10, 12])

In [180]:
arr % 2 ==0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [188]:
arr[(arr>3)&(arr<9)]

array([4, 5, 6, 7, 8])

In [192]:
import numpy as np
arr =np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
print(arr[0])    # 인덱스 0번 10
print(arr[-1])   # 제일 뒤 19
print(arr[0:3])  # [시작번호:끝번호+1] 10 11 12
print(arr[:3])   # 처음부터 3번 앞까지 10 11 12
print(arr[4:])   # 4번부터 끝까지 14 15 16 17 18 19
print(arr[4:6])  # 4번부터 6번 앞까지 14 15 
print(arr[4:-4]) # 4번부터 뒤에서 4번 앞까지 14 15

10
19
[10 11 12]
[10 11 12]
[14 15 16 17 18 19]
[14 15]
[14 15]
