## 넘파이 정렬
- 정렬은 배열 요소를 순서대로 배열하는 것을 말한다.
- 정렬된 순서는 숫자 또는 문자와 같은 요소를 오른차순 또는 내림차순 순서로 배열하는 것을 말한다.
- 넘파이 배열 객체에는 배열을 정렬하는 sort()라는 메서드가 있다.


### np.sort(), np.argsort() 매서드
- sort() 메서드 및 np.argsort() 메서드는 배열 데이터를 정렬하는데 매우 유용
    - np.sort(arr): 원본 데이터는 그대로 두고 임시로 정렬된 배열을 보여준다.
    - 배열명.sort(): 배열에 저장된 데이터를 정렬한 다음 정렬된 데이터를 저장
    - np.argsort(): 데이터가 정렬되었을 때의 각 데이터 위치(인덱스)를 반환

In [20]:
import numpy as np
arr = np.array([2,1,5,3,7,4,6,8])

print('arr:',arr)
print('np.sort:',np.sort(arr))  # 실제로 원본 데이터가 바뀌는건 아니다
arr2 =np.sort(arr)
print('arr:',arr)
print('arr2:',arr2)

arr: [2 1 5 3 7 4 6 8]
np.sort: [1 2 3 4 5 6 7 8]
arr: [2 1 5 3 7 4 6 8]
arr2: [1 2 3 4 5 6 7 8]


In [16]:
print('arr:',arr)
print('arr.sort:',arr.sort())  # 원본데이터가 바뀐다
print('arr:',arr)


arr: [2 1 5 3 7 4 6 8]
arr.sort: None
arr: [1 2 3 4 5 6 7 8]


In [22]:
print('원본=',arr)
print('정렬=',np.sort(arr))
print('위치=',np.argsort(arr))
print('원본=',arr)

원본= [2 1 5 3 7 4 6 8]
정렬= [1 2 3 4 5 6 7 8]
위치= [1 0 3 5 2 6 4 7]
원본= [2 1 5 3 7 4 6 8]


In [30]:
import numpy as np

# 학생 이름과 성적
students = np.array(["Alice","Bob",'Charlie','David','Eva'])
scores = np.array([88,92,75,95,85])

# 성적 정렬 및 원래 인덱스 찾기
sorted_indices = np.argsort(scores)
print(sorted_indices)

sorted_scores = np.sort(scores)
print(sorted_scores)

sorted_students = students[sorted_indices]  ## 원래 인덱스값을 통해 정렬된 점수와 매칭되도록 함
print(sorted_students)

# 결과 출력
print("학생 성적 정렬 결과:")
for i in range(len(sorted_scores)):
    print(f'{sorted_students[i]} : {sorted_scores[i]}점(원래 인덱스:{sorted_indices[i]})')

[2 4 0 1 3]
[75 85 88 92 95]
['Charlie' 'Eva' 'Alice' 'Bob' 'David']
학생 성적 정렬 결과:
Charlie : 75점(원래 인덱스:2)
Eva : 85점(원래 인덱스:4)
Alice : 88점(원래 인덱스:0)
Bob : 92점(원래 인덱스:1)
David : 95점(원래 인덱스:3)


### 2차원 배열 정렬

In [35]:
import numpy as np
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))
print(np.sort(arr,axis=1))
v
print(np.sort(arr,axis=0))

[[2 3 4]
 [0 1 5]]
[[2 3 4]
 [0 1 5]]
[[3 0 1]
 [5 2 4]]


In [41]:
import numpy as np
# 학생 성적: 행은 학생 ,열은 과목
scores =np.array([[88,92,75],
                  [85,90,95],
                  [78,88,80]])


# 각 과목별 성적 정렬
sorted_scores = np.sort(scores,axis=0) # 세로측
print("각 과목별 정렬된 성적:")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                l
print(sorted_scores)

각 과목별 정렬된 성적:
[[78 88 75]
 [85 90 80]
 [88 92 95]]


## 넘파이 병합
- 배열 병합은 두 개 이상의 배열의 값을 하나의 배열로 합치는 것
- 넘파이는 병합하려는 배열의 순서를 축과 함께concatente() 메서드에 전달한다. 축을 명확하게 입력하지 않으면 0으로 간주

In [51]:
import numpy as np
arr1 =np.array([1,2,3])
arr2 =np.array([4,5,6])

# [1, 2, 3]                [4, 5, 6]

arr = np.concatenate((arr1,arr2))  # 튜플 또는 리스트로 인자를 전달
#arr = np.concatenate((arr1,arr2),axis=0) 
print(arr)

# arr3 = np.concatenate((arr1,arr2),axis=1)  # 2차원 이상에서만
# print(arr3)

[1 2 3 4 5 6]


In [57]:
import numpy as np
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
'''
[1,2]                [5,6]
[3,4]                [7,8]   


[5,6]
[7,8]'''
arr = np.concatenate((arr1,arr2),axis=1)   # 가로축
print(arr)
print(arr.shape)

arr1 = np.concatenate((arr1,arr2),axis=0)  # 세로축
print(arr1)
print(arr1.shape)
                     

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [59]:
import numpy as np

# 상점 1의 제품 가격
store1_prices = np.array([[25000,27000], # 제품 1
                         [15000,16000]]) # 제품 2
# 상점 2의 제품 가격
store2_prices = np.array([[24000,26000], # 제품 1
                         [15500,16500]]) # 제품 2
combined_prices =np.concatenate((store1_prices,store2_prices),axis=0)
print("병합된 가격 정보:")
print(combined_prices)

병합된 가격 정보:
[[25000 27000]
 [15000 16000]
 [24000 26000]
 [15500 16500]]


In [65]:
import numpy as np

# 과목별 성적
math_scores = np.array([[85,90],   # 학생 1 
                        [78,82]])  # 학생 2
english_scores = np.array([[88,92],   # 학생 1 
                        [80,75]])  # 학생 2
combined_scores = np.concatenate((math_scores,english_scores),axis=1)
print("병합된 성적:")
print(combined_scores)

병합된 성적:
[[85 90 88 92]
 [78 82 80 75]]


## 넘파이 산술연산
- 산술 연산자 +,-,X,/ 를 사용하여 넘파이 배열들 간의 값을 계산
  

In [73]:
## 더하기
import numpy as np
arr1 =np.array([21, 22, 23, 24, 25])
arr2 =np.array([11, 12, 13, 14, 15])

newarr = arr1 + arr2
print(newarr)
newarr = np.add(arr1, arr2)
print(newarr)

[32 34 36 38 40]
[32 34 36 38 40]


In [81]:
## 빼기
newarr = arr1 - arr2
print(newarr)

newarr =np.subtract(arr1,arr2)
print(newarr)

[10 10 10 10 10]
[10 10 10 10 10]


In [83]:
## 곱하기
newarr = arr1 * arr2
print(newarr)

newarr =np.multiply(arr1,arr2)
print(newarr)

[231 264 299 336 375]
[231 264 299 336 375]


In [85]:
## 나누기 
newarr = arr1 / arr2
print(newarr)

newarr =np.divide(arr1,arr2)
print(newarr)

[1.90909091 1.83333333 1.76923077 1.71428571 1.66666667]
[1.90909091 1.83333333 1.76923077 1.71428571 1.66666667]


In [89]:
## 거듭제곱
arr1 =np.array([1, 2, 3, 4, 5])
arr2 =np.array([1, 2, 3, 4, 5])
newarr = arr1 * arr2
print(newarr)

newarr =np.power(arr1,arr2)
print(newarr)

[ 1  4  9 16 25]
[   1    4   27  256 3125]


In [93]:
# 나누기후 몫과 나머지
import numpy as np
arr1 = np.array([11,21,31,41,51])
arr2 =np.array([2,3,4,5,6])

newarr =np.divmod(arr1,arr2) # 몫과 나머지가 개별적인 배열로 튜플로 반환
print(newarr)

print(list(zip(arr1,arr2, *newarr)))

(array([5, 7, 7, 8, 8]), array([1, 0, 3, 1, 3]))
[(11, 2, 5, 1), (21, 3, 7, 0), (31, 4, 7, 3), (41, 5, 8, 1), (51, 6, 8, 3)]


In [95]:
# 절대값
import numpy as np
arr = np.array([1,-2, 3, -4, 5])

newarr=np.absolute(arr)
newarr

array([1, 2, 3, 4, 5])

## 넘파이 기술통계
- 넘파이는 데이터 집합에 대해 간단한 통계를 계산하는 매서드를 제공

In [102]:
import numpy as np
x= np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8, 2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])
print(np.sort(x))              
print(len(x))                  # 데이터 개수
print(sum(x))                  # 데이터 합계
print(np.mean(x))              # 평균
print(np.var(x))               # 분산(데이터의 흩어짐 정도를 나타내며, 평균으로부터의 거리의 제곱을 평균한 값)
print(np.std(x))               # 표준편차 (분산의 제곱근으로, 원래 단위로 데이터의 변동선을 나타냄)
print(np.max(x))               # 최대값
print(np.min(x))               # 최소값
print(np.median(x))            # 중앙값
print(np.percentile(x,25))     # 1사분위수
print(np.percentile(x,50))     # 2사분위수
print(np.percentile(x,75))     # 3사분위수
print(np.percentile(x,100))    # 4사분위수   


[-24 -13  -8  -7  -6  -1   0   0   2   2   4   4   5   5   5   7   8   9
  10  10  15  15  18  19  23  23]
26
125
4.8076923076923075
115.23224852071006
10.734628476137871
23
-24
5.0
0.0
5.0
10.0
23.0
